apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: k8s-express-tryout
          image: k8s-express-tryout
          ports:
            - containerPort: 3000
          env:
            - name: RESPONSE_MESSAGE
              valueFrom:
                secretKeyRef:
                  name:  express-secret
                  key: RESPONSE_MESSAGE
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: express-config
                  key: express-port
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080